// Generated by CoffeeScript 1.6.3
(function() {
  FoodApp.prototype.Application.routes.draw({
    resources: users
  }());

  root("users#new");

  match(" ", {
    to: "users#check_user",
    via: post
  });

  end;

}).call(this);
