// Generated by CoffeeScript 1.6.3
(function() {
  var SessionsController;

  (SessionsController = (function() {
    function SessionsController() {}

    return SessionsController;

  })()) < ApplicationController;

  end;

}).call(this);
